export const starterCards = [
  {
    id: 'kc-neo-001',
    name: 'Dracaufeu Holo Eclipse',
    set: 'Neo Tokyo Vault',
    rarity: 'Holo rare',
    type: 'Feu',
    condition: 'Near Mint',
    language: 'FR',
    grade: 'PSA 9',
    price: 189.9,
    stock: 2,
    reserved: false,
    status: 'available',
    reservedUntil: '',
    imageUrl: '',
    flaws: 'Micro-rayures visibles uniquement sous lumière forte.',
    privateNote: '',
    featured: true,
    color: '#e84842',
  },
  {
    id: 'kc-neo-002',
    name: 'Pikachu Sakura Foil',
    set: 'Hanami League',
    rarity: 'Illustration rare',
    type: 'Electrik',
    condition: 'Mint',
    language: 'JP',
    grade: 'Raw',
    price: 74.5,
    stock: 6,
    reserved: false,
    status: 'available',
    reservedUntil: '',
    imageUrl: '',
    flaws: 'Carte propre, centrage légèrement à droite.',
    privateNote: '',
    featured: true,
    color: '#f6c84f',
  },
  {
    id: 'kc-neo-003',
    name: 'Noctali Nuit Rouge',
    set: 'Shibuya Midnight',
    rarity: 'Secret rare',
    type: 'Tenebres',
    condition: 'Excellent',
    language: 'EN',
    grade: 'PSA 8',
    price: 129,
    stock: 1,
    reserved: false,
    status: 'available',
    reservedUntil: '',
    imageUrl: '',
    flaws: 'Légère trace sur le bord inférieur.',
    privateNote: '',
    featured: false,
    color: '#222631',
  },
  {
    id: 'kc-neo-004',
    name: 'Florizarre Jardin Ink',
    set: 'Kyoto Garden',
    rarity: 'Ultra rare',
    type: 'Plante',
    condition: 'Near Mint',
    language: 'FR',
    grade: 'Raw',
    price: 58,
    stock: 4,
    reserved: false,
    status: 'available',
    reservedUntil: '',
    imageUrl: '',
    flaws: 'Très bon état général.',
    privateNote: '',
    featured: false,
    color: '#2f9d73',
  },
  {
    id: 'kc-neo-005',
    name: 'Tortank Chrome Wave',
    set: 'Osaka Harbor',
    rarity: 'Holo rare',
    type: 'Eau',
    condition: 'Near Mint',
    language: 'JP',
    grade: 'PSA 9',
    price: 96.9,
    stock: 3,
    reserved: false,
    status: 'available',
    reservedUntil: '',
    imageUrl: '',
    flaws: 'Boîtier gradé propre.',
    privateNote: '',
    featured: true,
    color: '#367fd7',
  },
  {
    id: 'kc-neo-006',
    name: 'Mew Prisme Dojo',
    set: 'Kira Archive',
    rarity: 'Promo',
    type: 'Psy',
    condition: 'Mint',
    language: 'FR',
    grade: 'Raw',
    price: 42,
    stock: 8,
    reserved: false,
    status: 'available',
    reservedUntil: '',
    imageUrl: '',
    flaws: 'Aucun défaut majeur signalé.',
    privateNote: '',
    featured: false,
    color: '#e98ec8',
  },
]

export const starterSite = {
  dataVersion: 5,
  language: 'fr',
  colorMode: 'dark',
  brandName: 'HoloKira',
  brandMark: 'HK',
  adminPin: '1234',
  contactEmail: 'contact@holokira.eu',
  supportPhone: '+33 6 12 34 56 78',
  freeShippingFrom: 120,
  shippingFee: 6.9,
  lowStockLimit: 2,
  reservationHours: 48,
  theme: {
    red: '#db2a2a',
    ink: '#111318',
    paper: '#fbfaf6',
  },
  copy: {
    fr: {
      heroTitle: 'Cartes Pokémon premium',
      heroSubtitle:
        'Boutique européenne pour cartes gradées, singles rares et trouvailles japonaises sélectionnées à la main.',
      adminCta: "Ouvrir l'admin",
      searchPlaceholder: 'Rechercher une carte, un set ou une rareté...',
      cardsIntro: 'Vue rapide du stock disponible et des pièces à mettre en avant.',
      japaneseTitle: 'Cartes Pokémon japonaises',
      japaneseIntro:
        'Sélection de cartes japonaises, promos, holos et pièces modernes avec état annoncé clairement.',
      gradedTitle: 'Cartes Pokémon gradées',
      gradedIntro:
        'Cartes sous boîtier PSA ou équivalent, choisies pour les collectionneurs qui veulent une pièce prête à exposer.',
      ordersIntro: 'Tes réservations apparaîtront ici après validation de la demande.',
      sellTitle: 'Vendre tes cartes',
      sellIntro:
        'Propose tes cartes Pokémon à HoloKira pour une estimation claire, rapide et sans pression.',
      sellStepOne: 'Envoie la liste ou les photos de tes cartes.',
      sellStepTwo: 'Reçois une estimation basée sur l’état, la langue, la rareté et le marché.',
      sellStepThree: 'Valide la vente seulement si l’offre te convient.',
      aboutTitle: 'Une boutique pensée pour les collectionneurs européens',
      aboutIntro:
        'HoloKira sélectionne des cartes propres, vérifiées et présentées avec transparence pour les collectionneurs français et européens.',
      contactTitle: 'Contact',
      contactIntro:
        'Une question, une recherche précise ou une carte à proposer ? Écris-nous et nous répondrons rapidement.',
      legalTitle: 'Mentions légales et conditions',
      legalIntro: 'Informations à compléter avant la mise en ligne commerciale.',
      legalNotice:
        'Éditeur : HoloKira. Contact : contact@holokira.eu. Les informations de société devront être complétées avant publication.',
      terms:
        'Les prix sont indiqués en euros. Une réservation bloque temporairement la carte, puis le vendeur confirme les modalités par e-mail.',
      privacy:
        'Les données client servent uniquement au traitement des commandes, au suivi et au support.',
      returns:
        'Les retours et remboursements devront respecter la réglementation applicable aux ventes à distance.',
      checkoutTitle: 'Valider la réservation',
      checkoutIntro:
        'Renseigne tes informations et ajoute un message au vendeur. Aucun paiement ne se fait directement sur le site.',
      reservationMessagePlaceholder:
        'Exemple : Bonjour, je souhaite réserver ces cartes. Je suis disponible ce soir par e-mail.',
      paymentMode: 'Réservation sans paiement en ligne',
      paymentNote:
        'Après envoi, la carte passe en réservée et le vendeur te recontacte pour finaliser.',
      trustTitle: 'Achat clair, stock réel, envoi protégé',
      trustIntro:
        'Aucune fausse vente affichée : seules les réservations créées sur le site alimentent le panel admin.',
      emptyCart: 'Ajoute une carte pour préparer une réservation.',
      emptyOrders: 'Aucune réservation pour le moment.',
      footerNote: 'Expédition suivie depuis la France, protection rigide incluse.',
    },
    en: {
      heroTitle: 'Premium Pokémon cards',
      heroSubtitle:
        'A European boutique for graded cards, rare singles, and hand-picked Japanese finds.',
      adminCta: 'Open admin',
      searchPlaceholder: 'Search for a card, set, or rarity...',
      cardsIntro: 'Quick view of available stock and highlighted pieces.',
      japaneseTitle: 'Japanese Pokémon cards',
      japaneseIntro:
        'A selection of Japanese cards, promos, holos, and modern pieces with clearly stated condition.',
      gradedTitle: 'Graded Pokémon cards',
      gradedIntro:
        'PSA or equivalent graded cards selected for collectors who want display-ready pieces.',
      ordersIntro: 'Your reservations will appear here after submitting a request.',
      sellTitle: 'Sell your cards',
      sellIntro:
        'Offer your Pokémon cards to HoloKira for a clear, fast, no-pressure estimate.',
      sellStepOne: 'Send your card list or photos.',
      sellStepTwo: 'Get an estimate based on condition, language, rarity, and market demand.',
      sellStepThree: 'Accept only if the offer feels right.',
      aboutTitle: 'A shop built for European collectors',
      aboutIntro:
        'HoloKira selects clean, checked cards and presents them transparently for French and European collectors.',
      contactTitle: 'Contact',
      contactIntro:
        'Questions, a specific card request, or cards to sell? Message us and we will reply quickly.',
      legalTitle: 'Legal notice and terms',
      legalIntro: 'Information to complete before launching the shop commercially.',
      legalNotice:
        'Publisher: HoloKira. Contact: contact@holokira.eu. Company details must be completed before publication.',
      terms:
        'Prices are listed in euros. A reservation temporarily holds the card, then the seller confirms the next steps by email.',
      privacy:
        'Customer data is used only for order processing, tracking, and support.',
      returns:
        'Returns and refunds must follow the regulations applicable to distance selling.',
      checkoutTitle: 'Confirm reservation',
      checkoutIntro:
        'Enter your details and add a message for the seller. No payment is taken directly on the website.',
      reservationMessagePlaceholder:
        'Example: Hello, I would like to reserve these cards. I am available by email tonight.',
      paymentMode: 'Reservation without online payment',
      paymentNote:
        'After submission, the card becomes reserved and the seller will contact you to finalize.',
      trustTitle: 'Clear buying, real stock, protected shipping',
      trustIntro:
        'No fake sales are displayed: only reservations created on the site feed the admin panel.',
      emptyCart: 'Add a card to prepare a reservation.',
      emptyOrders: 'No reservations yet.',
      footerNote: 'Tracked shipping from France, rigid protection included.',
    },
  },
}

export const starterOrders = []

export const starterSellRequests = []
